apiVersion: v1
kind: Secret
metadata:
  name: dkusecret-doctor-train-3876h9x
type: Opaque
data:
  apiticket: WTdpeG5LaHkyZUthbmZ3RUdGSndXQnVjVkt0STZuTkNST0xvSHhTeFBxWDA4TEVqVmhxU1Q4UmNRVGhNdjBFZw== # base64